/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Visao.Cadastrar.CadastroProfessor;
import javax.swing.JOptionPane;

/**
 *
 * @author XPerience
 */
public class Disciplina extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Disciplina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CodigoDaDisciplina = new javax.swing.JLabel();
        campoCodigoProfessor = new javax.swing.JTextField();
        botaoProcurar = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        caixaÁrea = new javax.swing.JComboBox();
        botaoLimpar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoConsultar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        Área = new javax.swing.JLabel();
        CargaHorária = new javax.swing.JLabel();
        campoCargaHorária = new javax.swing.JTextField();
        Horas = new javax.swing.JLabel();
        Professores = new javax.swing.JLabel();
        caixaProfessores1 = new javax.swing.JComboBox();
        caixaProfessores2 = new javax.swing.JComboBox();
        caixaProfessores3 = new javax.swing.JComboBox();
        Fundo = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Professor = new javax.swing.JMenu();
        Assunto = new javax.swing.JMenu();
        Disciplina = new javax.swing.JMenu();
        Questão = new javax.swing.JMenu();
        Prova = new javax.swing.JMenu();
        Sobre = new javax.swing.JMenu();
        Sair = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Professor");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(460, 339));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        CodigoDaDisciplina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CodigoDaDisciplina.setText("Código do disciplina");
        jPanel2.add(CodigoDaDisciplina);
        CodigoDaDisciplina.setBounds(20, 20, 110, 15);
        jPanel2.add(campoCodigoProfessor);
        campoCodigoProfessor.setBounds(140, 10, 60, 30);

        botaoProcurar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoProcurar.setText("Procurar");
        jPanel2.add(botaoProcurar);
        botaoProcurar.setBounds(210, 10, 90, 30);
        jPanel2.add(campoNome);
        campoNome.setBounds(140, 50, 161, 30);

        Nome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Nome.setText("Nome");
        jPanel2.add(Nome);
        Nome.setBounds(20, 60, 32, 15);

        caixaÁrea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caixaÁrea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ciências da Natureza", "Ciências Humanas", "Curso de Agronegócio", "Curso de Eletrotécnica", "Curso de Enfermagem", "Curso de Informática", "Linguagens e Códigos", "Matemática" }));
        jPanel2.add(caixaÁrea);
        caixaÁrea.setBounds(140, 210, 161, 30);

        botaoLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });
        jPanel2.add(botaoLimpar);
        botaoLimpar.setBounds(220, 290, 90, 30);

        botaoCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoCancelar);
        botaoCancelar.setBounds(220, 330, 90, 30);

        botaoExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(botaoExcluir);
        botaoExcluir.setBounds(120, 330, 90, 30);

        botaoConsultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoConsultar.setText("Consultar");
        jPanel2.add(botaoConsultar);
        botaoConsultar.setBounds(120, 290, 90, 30);

        botaoCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCadastrar.setText("Cadastrar");
        jPanel2.add(botaoCadastrar);
        botaoCadastrar.setBounds(20, 290, 90, 30);

        botaoAtualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoAtualizar.setText("Atualizar");
        jPanel2.add(botaoAtualizar);
        botaoAtualizar.setBounds(20, 330, 90, 30);

        Área.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Área.setText("Área");
        jPanel2.add(Área);
        Área.setBounds(20, 220, 25, 20);

        CargaHorária.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CargaHorária.setText("Carga Horária");
        jPanel2.add(CargaHorária);
        CargaHorária.setBounds(20, 260, 80, 15);
        jPanel2.add(campoCargaHorária);
        campoCargaHorária.setBounds(140, 250, 50, 30);

        Horas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Horas.setText("horas de aula");
        jPanel2.add(Horas);
        Horas.setBounds(200, 260, 80, 15);

        Professores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Professores.setText("Professor(es):");
        jPanel2.add(Professores);
        Professores.setBounds(20, 100, 80, 15);

        caixaProfessores1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caixaProfessores1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nenhum", "Amanda Albuquerque", "Antonio Cosmo", "Arlindo Araújo", "Carlos Henrique", "Cláudio Matias", "Daniel Frutuoso", "Ednajar", "Elder", "Elieuza Rodrigues", "Emanuel Magalhães", "Emerson Teles", "Érica Nenes", "Felipe Alves", "Joarilúcio", "Leandro Paz", "Leidiane Vale", "Nábia Araújo", "Ozenário Abrantes", "Paulo Filho", "Paulo George", "Rafael Saraiva", "Ramon", "Roniele Rodrigues", "Sayonara Mineiro", "Suely Abrantes", "Vanessa Souza", "Talita" }));
        caixaProfessores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaProfessores1ActionPerformed(evt);
            }
        });
        jPanel2.add(caixaProfessores1);
        caixaProfessores1.setBounds(140, 170, 160, 30);

        caixaProfessores2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caixaProfessores2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amanda Albuquerque", "Antonio Cosmo", "Arlindo Araújo", "Carlos Henrique", "Cláudio Matias", "Daniel Frutuoso", "Ednajar", "Elder", "Elieuza Rodrigues", "Emanuel Magalhães", "Emerson Teles", "Érica Nenes", "Felipe Alves", "Joarilúcio", "Leandro Paz", "Leidiane Vale", "Nábia Araújo", "Ozenário Abrantes", "Paulo Filho", "Paulo George", "Rafael Saraiva", "Ramon", "Roniele Rodrigues", "Sayonara Mineiro", "Suely Abrantes", "Vanessa Souza", "Talita" }));
        caixaProfessores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaProfessores2ActionPerformed(evt);
            }
        });
        jPanel2.add(caixaProfessores2);
        caixaProfessores2.setBounds(140, 90, 160, 30);

        caixaProfessores3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caixaProfessores3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nenhum", "Amanda Albuquerque", "Antonio Cosmo", "Arlindo Araújo", "Carlos Henrique", "Cláudio Matias", "Daniel Frutuoso", "Ednajar", "Elder", "Elieuza Rodrigues", "Emanuel Magalhães", "Emerson Teles", "Érica Nenes", "Felipe Alves", "Joarilúcio", "Leandro Paz", "Leidiane Vale", "Nábia Araújo", "Ozenário Abrantes", "Paulo Filho", "Paulo George", "Rafael Saraiva", "Ramon", "Roniele Rodrigues", "Sayonara Mineiro", "Suely Abrantes", "Vanessa Souza", "Talita" }));
        caixaProfessores3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaProfessores3ActionPerformed(evt);
            }
        });
        jPanel2.add(caixaProfessores3);
        caixaProfessores3.setBounds(140, 130, 160, 30);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.jpg"))); // NOI18N
        jPanel2.add(Fundo);
        Fundo.setBounds(-410, 0, 1340, 460);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 860, 460);

        Professor.setText("Professor");
        Professor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfessorMouseClicked(evt);
            }
        });
        jMenuBar2.add(Professor);

        Assunto.setText("Assunto");
        Assunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssuntoMouseClicked(evt);
            }
        });
        jMenuBar2.add(Assunto);

        Disciplina.setText("Disciplina");
        jMenuBar2.add(Disciplina);

        Questão.setText("Questão");
        Questão.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuestãoMouseClicked(evt);
            }
        });
        jMenuBar2.add(Questão);

        Prova.setText("Prova");
        Prova.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProvaMouseClicked(evt);
            }
        });
        jMenuBar2.add(Prova);

        Sobre.setText("Sobre");
        jMenuBar2.add(Sobre);

        Sair.setText("Sair");
        jMenuBar2.add(Sair);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        campoCodigoProfessor.setText("");
        campoNome.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void AssuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssuntoMouseClicked
        Prova assunto = new Prova();
        assunto.setVisible(true);
        dispose();
    }//GEN-LAST:event_AssuntoMouseClicked

    private void ProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfessorMouseClicked
        Professor professor = new Professor();
        professor.setVisible(true);
        dispose();
    }//GEN-LAST:event_ProfessorMouseClicked

    private void QuestãoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuestãoMouseClicked
        Questão questao = new Questão();
        questao.setVisible(true);
        dispose();
    }//GEN-LAST:event_QuestãoMouseClicked

    private void ProvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProvaMouseClicked
        Prova prova = new Prova();
        prova.setVisible(true);
        dispose();
    }//GEN-LAST:event_ProvaMouseClicked

    private void caixaProfessores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaProfessores1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaProfessores1ActionPerformed

    private void caixaProfessores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaProfessores2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaProfessores2ActionPerformed

    private void caixaProfessores3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaProfessores3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaProfessores3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Disciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Disciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Disciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Disciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Disciplina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Assunto;
    private javax.swing.JLabel CargaHorária;
    private javax.swing.JLabel CodigoDaDisciplina;
    private javax.swing.JMenu Disciplina;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Horas;
    private javax.swing.JLabel Nome;
    private javax.swing.JMenu Professor;
    private javax.swing.JLabel Professores;
    private javax.swing.JMenu Prova;
    private javax.swing.JMenu Questão;
    private javax.swing.JMenu Sair;
    private javax.swing.JMenu Sobre;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoProcurar;
    private javax.swing.JComboBox caixaProfessores1;
    private javax.swing.JComboBox caixaProfessores2;
    private javax.swing.JComboBox caixaProfessores3;
    private javax.swing.JComboBox caixaÁrea;
    private javax.swing.JTextField campoCargaHorária;
    private javax.swing.JTextField campoCodigoProfessor;
    private javax.swing.JTextField campoNome;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel Área;
    // End of variables declaration//GEN-END:variables
}
