/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Visao.Cadastrar.CadastroProfessor;
import javax.swing.JOptionPane;

/**
 *
 * @author XPerience
 */
public class Professor extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Professor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CodigoDoProfessor = new javax.swing.JLabel();
        campoCodigoProfessor = new javax.swing.JTextField();
        botaoProcurar = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        Senha = new javax.swing.JLabel();
        Contato = new javax.swing.JLabel();
        caixaDisciplina1 = new javax.swing.JComboBox();
        caixaDisciplina2 = new javax.swing.JComboBox();
        botaoLimpar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoConsultar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        Sexo = new javax.swing.JLabel();
        caixaSexo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        Professor = new javax.swing.JMenu();
        Assunto = new javax.swing.JMenu();
        Disciplina = new javax.swing.JMenu();
        Questão = new javax.swing.JMenu();
        Prova = new javax.swing.JMenu();
        Sobre = new javax.swing.JMenu();
        Sair = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Professor");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(460, 339));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        CodigoDoProfessor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CodigoDoProfessor.setText("Código do professor");
        jPanel2.add(CodigoDoProfessor);
        CodigoDoProfessor.setBounds(570, 20, 109, 15);
        jPanel2.add(campoCodigoProfessor);
        campoCodigoProfessor.setBounds(690, 10, 60, 30);

        botaoProcurar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoProcurar.setText("Procurar");
        jPanel2.add(botaoProcurar);
        botaoProcurar.setBounds(760, 10, 90, 30);
        jPanel2.add(campoNome);
        campoNome.setBounds(690, 50, 161, 30);

        Nome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Nome.setText("Nome");
        jPanel2.add(Nome);
        Nome.setBounds(570, 60, 32, 15);

        Login.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Login.setText("Login");
        jPanel2.add(Login);
        Login.setBounds(570, 140, 29, 15);
        jPanel2.add(campoLogin);
        campoLogin.setBounds(690, 130, 161, 30);
        jPanel2.add(campoSenha);
        campoSenha.setBounds(690, 170, 161, 30);

        Senha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Senha.setText("Senha");
        jPanel2.add(Senha);
        Senha.setBounds(570, 180, 34, 15);

        Contato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Contato.setText("Contato");
        jPanel2.add(Contato);
        Contato.setBounds(570, 300, 44, 15);

        caixaDisciplina1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caixaDisciplina1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matemática", "Química", "Física", "Biologia", "História", "Geografia", "Sociologia", "Filosofia", "Português", "Espanhol", "Inglês", "Educação Física", "Informática Básica", "Lógica de Programação", "HTML/CSS", "PHP/MySQL", "Banco de Dados", "POO/Java", "Laboratório Hardware", "Laboratório Software", "Laboratório Web" }));
        jPanel2.add(caixaDisciplina1);
        caixaDisciplina1.setBounds(690, 210, 161, 30);

        caixaDisciplina2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caixaDisciplina2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nenhuma", "Matemática", "Química", "Física", "Biologia", "História", "Geografia", "Sociologia", "Filosofia", "Português", "Espanhol", "Inglês", "Educação Física", "Informática Básica", "Lógica de Programação", "HTML/CSS", "PHP/MySQL", "Banco de Dados", "POO/Java", "Laboratório Hardware", "Laboratório Software", "Laboratório Web" }));
        jPanel2.add(caixaDisciplina2);
        caixaDisciplina2.setBounds(690, 250, 161, 30);

        botaoLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });
        jPanel2.add(botaoLimpar);
        botaoLimpar.setBounds(760, 380, 90, 30);

        botaoCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoCancelar);
        botaoCancelar.setBounds(760, 420, 90, 30);

        botaoExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(botaoExcluir);
        botaoExcluir.setBounds(660, 420, 90, 30);

        botaoConsultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoConsultar.setText("Consultar");
        jPanel2.add(botaoConsultar);
        botaoConsultar.setBounds(660, 380, 90, 30);

        botaoCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCadastrar.setText("Cadastrar");
        jPanel2.add(botaoCadastrar);
        botaoCadastrar.setBounds(560, 380, 90, 30);

        botaoAtualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoAtualizar.setText("Atualizar");
        jPanel2.add(botaoAtualizar);
        botaoAtualizar.setBounds(560, 420, 90, 30);

        Sexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Sexo.setText("Sexo");
        jPanel2.add(Sexo);
        Sexo.setBounds(570, 100, 27, 15);

        caixaSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caixaSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", "Outro" }));
        caixaSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaSexoActionPerformed(evt);
            }
        });
        jPanel2.add(caixaSexo);
        caixaSexo.setBounds(690, 90, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Disciplina");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(570, 220, 47, 20);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(690, 290, 40, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 860, 460);

        Professor.setText("Professor");
        jMenuBar2.add(Professor);

        Assunto.setText("Assunto");
        jMenuBar2.add(Assunto);

        Disciplina.setText("Disciplina");
        jMenuBar2.add(Disciplina);

        Questão.setText("Questão");
        jMenuBar2.add(Questão);

        Prova.setText("Prova");
        jMenuBar2.add(Prova);

        Sobre.setText("Sobre");
        jMenuBar2.add(Sobre);

        Sair.setText("Sair");
        jMenuBar2.add(Sair);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        campoCodigoProfessor.setText("");
        campoNome.setText("");
        campoLogin.setText("");
        campoSenha.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void caixaSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaSexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Assunto;
    private javax.swing.JLabel CodigoDoProfessor;
    private javax.swing.JLabel Contato;
    private javax.swing.JMenu Disciplina;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Nome;
    private javax.swing.JMenu Professor;
    private javax.swing.JMenu Prova;
    private javax.swing.JMenu Questão;
    private javax.swing.JMenu Sair;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel Sexo;
    private javax.swing.JMenu Sobre;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoProcurar;
    private javax.swing.JComboBox caixaDisciplina1;
    private javax.swing.JComboBox caixaDisciplina2;
    private javax.swing.JComboBox caixaSexo;
    private javax.swing.JTextField campoCodigoProfessor;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
